### PR TITLE
Rename `oneOf` to `oneOfType` and implement `oneOf`

### LINKED ISSUE #10: Rename `oneOf` to `oneOfType`
For more consistency with React's propTypes. https://facebook.github.io/react/docs/reusable-components.html#prop-validation

`oneOf` enforces that the property is one of the specified values. 
`oneOfType` enforces that the property is one of the specified types.

### PR DESCRIPTION
**Pull request by philpee2**
This API is more consistent with React

#MAJOR#

Resolves #10

### CODE REVIEW

**Comment by sandersky** [comment]
:+1:

**Comment by sandersky** [comment]
@philpee2 it looks like you need to merge with upstream.

**Comment by philpee2** [comment]
@sandersky Done

**Comment by sandersky** [comment]
:+1:

**Pull request merged**
